/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SIMPLECALC_PRIVATE_H
#define SIMPLECALC_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.0.0.0"
#define VER_MAJOR	2
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"2.0.0.0"
#define FILE_DESCRIPTION	"Simplecalc"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"2.0.0.0"

#endif /*SIMPLECALC_PRIVATE_H*/
